### ISSUE TITLE
ctex宏包报错

### ISSUE THREAD

**Issue by Mooto-L** [andy123t/shnuthesis#2]
你好，先谢谢您！请问编译时出现这样的报错该怎么办？（是ctex没有cs4size选项，担心会是其他地方的问题所以都贴过来了，这是用ctex编译的报错，用texlive也是卡在这里，重装了才发现是模板里面出现的cs4size）
Command Line:   xelatex.exe --interaction=errorstopmode --synctex=1 "test.tex"
Startup Folder: D:\研\毕业论文\shnuthesis-master

Qt: Untested Windows version 6.2 detected!
This is XeTeX, Version 3.1415926-2.3-0.9997.5 (MiKTeX 2.9)
entering extended mode
(D:\研\毕业论文\shnuthesis-master\test.tex
LaTeX2e <2011/06/27>
Babel <v3.8m> and hyphenation patterns for loaded.
(D:\研\毕业论文\shnuthesis-master\shnuthesis.cls
Document Class: shnuthesis 2021/06/03 v2.0.0
(D:\CTEX\MiKTeX\tex\latex\base\book.cls
Document Class: book 2007/10/19 v1.4h Standard LaTeX document class
(D:\CTEX\MiKTeX\tex\latex\base\bk10.clo))
(D:\CTEX\MiKTeX\tex\latex\ctex\ctex.sty
(D:\CTEX\MiKTeX\tex\latex\ctex\opt\ctex-common-opts.def)
(D:\CTEX\CTeX\tex\latex\ctex\cfg\ctexopts.cfg)

! LaTeX Error: Unknown option `cs4size' for package `ctex'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.13 
     
?

**Comment by andy123t** [comment]
模板的最新版本已经去掉 ctex  宏包的 cs4size 选项 (ctex 宏包会逐渐取消 cs4size 选项，现在还没取消)，你用的模板应该是之前下载的版本，你可以下载最新版。

对于之前的版本 (有 cs4size 选项)，我在 texlive 2020 和 texlive 2021 都测试过，没有问题。

注意：不要使用 CTEX套装，使用 texlive，如果安装 texlive 要把 CTEX 卸载干净。

**Comment by Mooto-L** [comment]
谢谢谢谢！我就去下载新模板用。
之前的版本，用texlive编译的时候可能是因为我不会设置xe-bib-xe-xe模式直接用xelatex编译导致的，因为后来用vscode按这个配方编译就可以出结果。
现在texlive和ctex都装了，再把ctex卸载掉，应该不会影响texlive吧？



---Original---
From: "Liutao ***@***.***&gt;
Sent at: 2022年1月18日(Tue) Noon12:58
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [andy123t/shnuthesis] ctex宏包报错 (Issue #2)




 
模板的最新版本已经去掉 ctex  宏包的 cs4size 选项 (ctex 宏包会逐渐取消 cs4size 选项，现在还没取消)，你用的模板应该是之前下载的版本，你可以下载最新版。
 
对于之前的版本 (有 cs4size 选项)，我在 texlive 2020 和 texlive 2021 都测试过，没有问题。
 
注意：不要使用 CTEX套装，使用 texlive，如果安装 texlive 要把 CTEX 卸载干净。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by andy123t** [comment]
先卸载 CTEX 套装，再安装 texlive 没有问题，
可以使用 texstudio 编辑器，比较方便。

如果使用 texlive + Winedt + SumatraPDF 会麻烦一点，vscode 也很麻烦，懒得折腾。

**Comment by Mooto-L** [comment]
嗯嗯嗯，感谢您



---Original---
From: "Liutao ***@***.***&gt;
Sent at: 2022年1月18日(Tue) Noon1:57
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [andy123t/shnuthesis] ctex宏包报错 (Issue #2)




 
先卸载 CTEX 套装，再安装 texlive 没有问题，
 可以使用 texstudio 编辑器，比较方便。
 
如果使用 texlive + Winedt + SumatraPDF 会麻烦一点，vscode 也很麻烦，懒得折腾。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
