### ISSUE TITLE
本科毕业论文 latex 模板

### ISSUE THREAD

**Issue by heqin-zhu** [andy123t/shnuthesis#3]
学长，你好！很感谢你能开发这样的研究生毕业论文模板。我想问一下，上海师范大学本科毕业论文有latex 模板吗？学长可以考虑开发一下吗？非常感谢！

**Comment by andy123t** [comment]
没有本科毕业论文的规范和格式，没办法开发。

**Comment by heqin-zhu** [comment]
感谢学长开发出[本科生毕业论文 LaTeX 模板](https://github.com/andy123t/shnubachelor)
