### ISSUE TITLE
核心内容是.bst文件吗？这个怎么生成的？

### ISSUE THREAD

**Issue by 14790897** [andy123t/shnuthesis#4]
shnuthesis-numeric.bst
shnuthesis-author-year.bst
提问

**Comment by andy123t** [comment]
.bst 文件是参考文献的格式文件， 比如 shnuthesis-numeric.bst 是在 thuthesis-numeric.bst 的基础上修改的，符合 GB/T 7714—2015 文献标准，其实也可以直接使用 gbt7714-numerical.bst，格式会有一些差别。如果想修改可以学习一下，在这些基础上修改。

**Comment by 14790897** [comment]
好的
